import fs from 'node:fs';
const FILE='dist/index.html',PACKS='football-db/research-packs.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/championship-research-queue.json',INTAKE='football-db/championship-research-intake.json',VALIDATION='football-db/research-expansion-validation.json',IDENTITIES='football-db/identities.json',MANIFEST='football-db/manifest.json',BUILD='v1.90.0';
for(const file of [FILE,PACKS,COVERAGE,QUEUE,INTAKE,VALIDATION,IDENTITIES,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.89.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.89.0 output was not found.`);
const packs=JSON.parse(fs.readFileSync(PACKS,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8')),identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-research.21')throw new Error(`SWOS Studio ${BUILD} build failed: expected research DB .21; found ${manifest.version}.`);
if(!packs.clubs?.['west-bromwich-albion']||Object.keys(packs.clubs['west-bromwich-albion'].players||{}).length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: West Brom research pack missing or incomplete.`);
const identityNames=new Set((identities.clubs?.['west-bromwich-albion']||[]).map(p=>p.footballName)),researchNames=new Set(Object.keys(packs.clubs['west-bromwich-albion'].players||{}));
for(const stale of ['Krystian Bielik','Alfie Gilchrist','Alex Mowatt'])if(identityNames.has(stale)||researchNames.has(stale))throw new Error(`SWOS Studio ${BUILD} build failed: stale West Brom player ${stale} survived correction.`);
for(const current of ['Brayann Pereira','Nolan Galves','Toby Collyer'])if(!identityNames.has(current)||!researchNames.has(current))throw new Error(`SWOS Studio ${BUILD} build failed: corrected West Brom player ${current} is missing.`);
if(identityNames.size!==16||researchNames.size!==16)throw new Error(`SWOS Studio ${BUILD} build failed: West Brom identity/research sets must both contain exactly 16 players.`);
for(const name of identityNames)if(!researchNames.has(name))throw new Error(`SWOS Studio ${BUILD} build failed: West Brom research pack is missing identity player ${name}.`);
if(packs.packCount!==41||packs.playerCount!==656)throw new Error(`SWOS Studio ${BUILD} build failed: expected 41 research packs / 656 players; found ${packs.packCount} / ${packs.playerCount}.`);
if(pl?.researchReady!==20||champ?.identityReady!==24||champ?.researchReady!==21)throw new Error(`SWOS Studio ${BUILD} build failed: expected PL 20/20 and Championship 21/24 research.`);
if(queue.progress?.researchReadyClubs!==21||queue.totals?.clubs!==3||queue.totals?.stagedPlayers!==48||queue.totals?.requiredEvidenceCells!==144||queue.next?.clubId!=='west-ham-united')throw new Error(`SWOS Studio ${BUILD} build failed: pending Championship queue should be 3 clubs with West Ham United next.`);
if(intake.progress?.researchReadyClubs!==21||intake.progress?.researchPendingClubs!==3||intake.totals?.clubs!==3||intake.totals?.players!==48||intake.totals?.requiredEvidenceCells!==144)throw new Error(`SWOS Studio ${BUILD} build failed: Championship intake progress is stale.`);
if(validation.status!=='pass'||validation.divisions?.premierLeague?.researchReady!==20||validation.divisions?.championship?.researchReady!==21||validation.totals?.researchClubs!==41||validation.totals?.researchPlayers!==656)throw new Error(`SWOS Studio ${BUILD} build failed: research expansion validation is stale.`);
if(manifest.installation?.teamWriteReady!==false||manifest.installation?.careerWriteReady!==false)throw new Error(`SWOS Studio ${BUILD} build failed: binary write locks changed unexpectedly.`);
html=html.replace('<title>SWOS Studio v1.89.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={champReady:21,totalResearchClubs:41,totalResearchPlayers:656,next:queue.next.clubName},embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v190-west-brom-research-layer">
(function(){'use strict';var BUILD='v1.90.0',META=${embedded};
function render(){var anchor=document.getElementById('v189-watford-research')||document.getElementById('v188-swansea-research');if(!anchor)return false;
if(!document.getElementById('v190-west-brom-research')){var box=document.createElement('div');box.id='v190-west-brom-research';box.className='card stack';box.innerHTML='<strong>✅ West Bromwich Albion research pack promoted</strong><span class="about">The post-window guard removes Bielik, Gilchrist and Mowatt, then replaces them one-for-one with current West Brom players Pereira, Galves and Collyer before the exact-16 evidence gate passes.</span><span class="about">Championship research coverage: <b>'+META.champReady+' / 24</b>. England now carries <b>'+META.totalResearchClubs+' research-ready clubs / '+META.totalResearchPlayers+' researched players</b>.</span><span class="about">Next evidence target: <b>'+META.next+'</b>. Three Championship clubs remain.</span><span class="feature-status available">21 / 24 CHAMPIONSHIP RESEARCH READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v190-release-card')){var a=document.getElementById('v189-release-card')||document.getElementById('v188-release-card');if(a){var c=document.createElement('div');c.id='v190-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.90.0 — West Brom roster correction + research promotion</strong><span class="about">• Three stale selected identities are removed before publication.</span><span class="about">• Brayann Pereira and Nolan Galves restore current defender slots; Toby Collyer restores the midfield slot.</span><span class="about">• Isaac Price\'s snapshot age advances to 23 after his 26 September birthday.</span><span class="about">• Championship research reaches 21 / 24; West Ham United is next.</span><span class="about">• Only 48 staged Championship players / 144 mandatory evidence cells remain.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v190-west-brom-research-layer')||!html.includes('<title>SWOS Studio v1.90.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: West Brom research layer missing.`);
console.log(`SWOS Studio v1.90.0 West Brom research promotion complete · Championship 21/24 · all research 41 clubs / 656 players · next ${queue.next.clubName} · binary writes locked.`);
