import fs from 'node:fs';

const FILE='dist/index.html',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/identity-expansion-queue.json',INTAKE='football-db/identity-intake.json',MANIFEST='football-db/manifest.json',VALIDATION='football-db/validation.json';
const BUILD='v1.64.0';
for(const file of [FILE,IDENTITIES,COVERAGE,QUEUE,INTAKE,MANIFEST,VALIDATION])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');if(!html.includes('<title>SWOS Studio v1.63.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.63.0 output was not found.`);
const identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-identity.35')throw new Error(`SWOS Studio ${BUILD} build failed: expected england identity DB .35; found ${manifest.version}.`);
if(!Array.isArray(identities.clubs?.['queens-park-rangers'])||identities.clubs['queens-park-rangers'].length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Queens Park Rangers is not a validated 16-player identity pack.`);
if(identities.clubCount!==35||identities.playerCount!==615||identities.divisionCoverage?.championship?.clubs!==15||identities.divisionCoverage?.championship?.players!==240)throw new Error(`SWOS Studio ${BUILD} build failed: expected 35 England identity clubs / 615 players with 15 Championship clubs.`);
if(champ?.identityReady!==15||champ?.researchReady!==0||pl?.identityReady!==20||pl?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: expected Championship 15 identity-ready / 0 research-ready and Premier League 20 / 20.`);
if(coverage.summary?.identityReady!==35||coverage.summary?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: England coverage summary is inconsistent.`);
if(queue.totals?.identityReady!==15||queue.totals?.evidenceRequired!==9||!queue.next?.clubId||queue.next.clubId==='queens-park-rangers')throw new Error(`SWOS Studio ${BUILD} build failed: Championship queue did not advance beyond Queens Park Rangers.`);
if(intake.totals?.identityReady!==15||!intake.next?.clubId||intake.next.clubId==='queens-park-rangers')throw new Error(`SWOS Studio ${BUILD} build failed: final identity intake did not advance beyond Queens Park Rangers.`);
if(validation.status!=='pass'||validation.totals?.identityClubs!==35||validation.totals?.championshipIdentityClubs!==15)throw new Error(`SWOS Studio ${BUILD} build failed: identity expansion validation is stale.`);
html=html.replace('<title>SWOS Studio v1.63.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={englandIdentityClubs:identities.clubCount,englandIdentityPlayers:identities.playerCount,champReady:champ.identityReady,next:queue.next.clubName,plResearch:pl.researchReady,databaseVersion:manifest.version};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v164-qpr-layer">
(function(){
'use strict';var BUILD='v1.64.0',META=${embedded};function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function render(){var panel=document.getElementById('v159-championship-identity');if(panel){var head=panel.querySelector('.v159-head div');if(head)head.innerHTML='<strong>🏆 Championship Identity Expansion — '+META.champReady+' / 24 Complete</strong><p>Queens Park Rangers has cleared the guarded 2026/27 identity pipeline. Fifteen Championship clubs are now identity-ready while research remains correctly held behind the evidence gate.</p>';var stats=panel.querySelector('.v159-stats');if(stats)stats.innerHTML='<div class="v159-stat"><small>England identity</small><b>'+META.englandIdentityClubs+' / 92</b></div><div class="v159-stat"><small>Championship ready</small><b>'+META.champReady+' / 24</b></div><div class="v159-stat"><small>PL research</small><b>'+META.plResearch+' / 20 ✓</b></div><div class="v159-stat"><small>Next club</small><b>'+esc(META.next)+'</b></div>';}
var anchor=document.getElementById('v163-preston-summary')||document.getElementById('v162-portsmouth-summary')||panel;if(!anchor)return false;if(!document.getElementById('v164-qpr-summary')){var box=document.createElement('div');box.id='v164-qpr-summary';box.className='card stack';box.innerHTML='<strong>Queens Park Rangers identity pack validated</strong><span class="about">A current 2026/27 QPR 16-player identity pack has passed the evidence intake and promotion guard, including current goalkeeper-number cross-checking.</span><span class="about">England now carries '+META.englandIdentityPlayers+' selected identities across '+META.englandIdentityClubs+' clubs. Championship coverage stands at '+META.champReady+' / 24, with '+esc(META.next)+' next.</span><span class="feature-status available">15 / 24 IDENTITY READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v164-release-card')){var a=document.getElementById('v163-release-card')||document.getElementById('v162-release-card');if(a){var c=document.createElement('div');c.id='v164-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.64.0 — Queens Park Rangers identity pack</strong><span class="about">• QPR passes the evidence-gated 16-player current-squad pipeline.</span><span class="about">• Championship identity coverage moves to 15 / 24; England reaches 35 / 92 clubs and 615 selected identities.</span><span class="about">• Exact-16, source, uniqueness, shirt and role-balance checks remain mandatory.</span><span class="about">• The next identity target is '+esc(META.next)+'.</span><span class="about">• Premier League research remains complete at 20 / 20; Championship research stays blocked until identity coverage is ready.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');if(!html.includes('swos-v164-qpr-layer')||!html.includes('<title>SWOS Studio v1.64.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: QPR layer missing.`);
console.log(`SWOS Studio ${BUILD} Queens Park Rangers identity expansion complete · 15/24 ready · England ${identities.clubCount}/92 identity clubs · next ${queue.next.clubName}.`);
