import fs from 'node:fs';

const FILE='dist/index.html';
const IDENTITIES='football-db/identities.json';
const COVERAGE='football-db/coverage.json';
const QUEUE='football-db/identity-expansion-queue.json';
const INTAKE='football-db/identity-intake.json';
const MANIFEST='football-db/manifest.json';
const BUILD='v1.59.0';
for(const file of [FILE,IDENTITIES,COVERAGE,QUEUE,INTAKE,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.58.1</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.58.1 output was not found.`);
const identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1);
if(manifest.version!=='2026.27-england-identity.21')throw new Error(`SWOS Studio ${BUILD} build failed: expected england identity DB .21; found ${manifest.version}.`);
if(identities.clubCount!==21||identities.playerCount!==391||identities.divisionCoverage?.championship?.clubs!==1)throw new Error(`SWOS Studio ${BUILD} build failed: expected 21 England identity clubs / 391 players with 1 Championship club.`);
if(champ?.identityReady!==1||champ?.researchReady!==0)throw new Error(`SWOS Studio ${BUILD} build failed: Championship coverage must be 1 identity-ready / 0 research-ready.`);
if(queue.totals?.identityReady!==1||queue.totals?.evidenceRequired!==23||queue.next?.clubId!=='blackburn-rovers')throw new Error(`SWOS Studio ${BUILD} build failed: Championship queue should advance to Blackburn Rovers.`);
if(intake.totals?.identityReady!==1||intake.totals?.promotionReadyClubs!==0)throw new Error(`SWOS Studio ${BUILD} build failed: final identity intake should show Birmingham published and no second club auto-promoted.`);
html=html.replace('<title>SWOS Studio v1.58.1</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={englandIdentityClubs:identities.clubCount,englandIdentityPlayers:identities.playerCount,champReady:queue.totals.identityReady,champPending:queue.totals.evidenceRequired,next:queue.next.clubName,plResearch:coverage.divisions.find(d=>d.code===0)?.researchReady||0,databaseVersion:manifest.version};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const css=String.raw`
<style id="swos-v159-championship-identity-styles">
.v159-panel{border:1px solid rgba(80,190,255,.42);background:linear-gradient(180deg,rgba(20,100,160,.12),rgba(7,17,31,.98));border-radius:14px;padding:13px;margin:10px 0;box-shadow:var(--shadow)}
.v159-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.v159-head p{font-size:9px;color:var(--muted);line-height:1.45;margin:4px 0 0}.v159-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.v159-stat{border:1px solid var(--line);border-radius:10px;padding:9px;background:rgba(5,15,28,.72)}.v159-stat small{display:block;color:var(--muted);font-size:7px;text-transform:uppercase}.v159-stat b{display:block;margin-top:4px;font-size:13px}.v159-editor{margin-top:10px;border-top:1px solid var(--line);padding-top:10px}.v159-form{display:grid;grid-template-columns:1.25fr .8fr .9fr .55fr;gap:7px}.v159-form .wide{grid-column:1/-1}.v159-form label{font-size:7px;text-transform:uppercase;color:var(--muted);display:block;margin-bottom:3px}.v159-form input,.v159-form select{width:100%;height:38px;border-radius:8px;border:1px solid var(--line);background:#07111f;color:var(--text);padding:0 8px}.v159-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.v159-actions .btn{flex:1;min-height:38px;font-size:9px}.v159-list{margin-top:8px;font-size:8px;line-height:1.5;color:var(--muted);max-height:150px;overflow:auto}.v159-status{font-size:8px;color:var(--muted);margin-top:7px}.v159-status b{color:var(--text)}
@media(max-width:700px){.v159-stats{grid-template-columns:1fr 1fr}.v159-form{grid-template-columns:1fr 1fr}}
</style>`;
html=html.replace('</head>',css+'\n</head>');
const js=String.raw`
<script id="swos-v159-championship-identity-layer">
(function(){
'use strict';var BUILD='v1.59.0',META=${embedded},QUEUE_URL='football-db/identity-expansion-queue.json',STORE='swos-identity-evidence:v1:';var q=null,club=null;
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function load(id){try{return JSON.parse(localStorage.getItem(STORE+id)||'{"players":[]}')}catch(e){return {players:[]}}}function save(id,d){localStorage.setItem(STORE+id,JSON.stringify(d));}
function roleCounts(rows){var c={Goalkeeper:0,Defender:0,Midfielder:0,Forward:0};rows.forEach(function(r){if(c[r.group]!=null)c[r.group]++;});return c;}function valid(rows){var c=roleCounts(rows),names=new Set(rows.map(function(r){return String(r.footballName||'').trim().toLowerCase();}));return rows.length===16&&names.size===16&&c.Goalkeeper>=2&&c.Defender>=4&&c.Midfielder>=4&&c.Forward>=2&&rows.every(function(r){return r.footballName&&r.group&&r.nationality&&r.source;});}
function status(msg){var el=document.getElementById('v159Status');if(!el||!club)return;var d=load(club.clubId),c=roleCounts(d.players||[]);el.innerHTML=(msg?'<b>'+esc(msg)+'</b><br>':'')+'Local '+esc(club.clubName)+' draft: <b>'+(d.players||[]).length+' / 16</b> · GK '+c.Goalkeeper+' · DEF '+c.Defender+' · MID '+c.Midfielder+' · FWD '+c.Forward+(valid(d.players||[])?' · <b>promotion schema complete ✓</b>':'');var list=document.getElementById('v159List');if(list)list.innerHTML=(d.players||[]).map(function(r,i){return (i+1)+'. '+esc(r.footballName)+' · '+esc(r.group)+' · '+esc(r.nationality)+(r.shirt?' · #'+r.shirt:'');}).join('<br>')||'No local identity rows yet.';}
function clearForm(){['v159Name','v159Nat','v159Shirt','v159Source'].forEach(function(id){var e=document.getElementById(id);if(e)e.value='';});var g=document.getElementById('v159Group');if(g)g.value='Defender';}
function render(){var anchor=document.getElementById('v1581-static-db-note')||document.getElementById('v146-data-expansion')||document.getElementById('v145-workbench');if(!anchor||document.getElementById('v159-championship-identity'))return false;var box=document.createElement('section');box.id='v159-championship-identity';box.className='v159-panel';box.innerHTML='<div class="v159-head"><div><strong>🏆 Championship Identity Expansion</strong><p>The Premier League research foundation is complete, so the database has moved into the Championship. Birmingham City is the first evidence-gated identity pack. The next 23 clubs stay blocked until 16 sourced current identities pass the same guard.</p></div><span class="feature-status beta">IDENTITY EXPANSION</span></div><div class="v159-stats"><div class="v159-stat"><small>England identity</small><b>'+META.englandIdentityClubs+' / 92</b></div><div class="v159-stat"><small>Championship ready</small><b>'+META.champReady+' / 24</b></div><div class="v159-stat"><small>PL research</small><b>'+META.plResearch+' / 20 ✓</b></div><div class="v159-stat"><small>Next club</small><b>'+esc(META.next)+'</b></div></div><div class="v159-editor"><strong>Identity Evidence Editor</strong><div class="v159-form"><div><label>Club</label><select id="v159Club"></select></div><div><label>Player name</label><input id="v159Name" placeholder="Current football name"></div><div><label>Broad role</label><select id="v159Group"><option>Goalkeeper</option><option selected>Defender</option><option>Midfielder</option><option>Forward</option></select></div><div><label>Shirt</label><input id="v159Shirt" inputmode="numeric" placeholder="optional"></div><div><label>Nationality</label><input id="v159Nat" placeholder="e.g. England"></div><div class="wide"><label>Evidence source</label><input id="v159Source" placeholder="Current squad / registration source"></div></div><div class="v159-actions"><button class="btn btn-green" id="v159Add">Add identity</button><button class="btn" id="v159Undo">Remove last</button><button class="btn btn-blue" id="v159Export">Export club evidence</button><button class="btn" id="v159Import">Import evidence</button><input class="hidden" type="file" accept="application/json,.json" id="v159File"></div><div class="v159-status" id="v159Status"></div><div class="v159-list" id="v159List"></div></div>';anchor.insertAdjacentElement('afterend',box);
var sel=document.getElementById('v159Club'),pending=(q.queue||[]).filter(function(c){return c.status!=='identity-ready';});sel.innerHTML=pending.map(function(c){return '<option value="'+esc(c.clubId)+'">'+esc(c.clubName)+'</option>';}).join('');club=pending[0]||null;status();sel.onchange=function(){club=pending.find(function(c){return c.clubId===sel.value;})||pending[0];status();};
document.getElementById('v159Add').onclick=function(){if(!club)return;var name=document.getElementById('v159Name').value.trim(),group=document.getElementById('v159Group').value,nat=document.getElementById('v159Nat').value.trim(),source=document.getElementById('v159Source').value.trim(),shirtRaw=document.getElementById('v159Shirt').value.trim();if(!name||!nat||!source){status('Name, nationality and source are required.');return;}var d=load(club.clubId);d.players=d.players||[];if(d.players.length>=16){status('This draft already has 16 identities. Remove one before adding another.');return;}if(d.players.some(function(r){return r.footballName.toLowerCase()===name.toLowerCase();})){status('That player is already in the draft.');return;}var row={footballName:name,group:group,nationality:nat,source:source};if(shirtRaw){var s=Number(shirtRaw);if(!Number.isInteger(s)||s<1||s>99){status('Shirt number must be 1–99 or blank.');return;}row.shirt=s;}d.players.push(row);save(club.clubId,d);clearForm();status('Added '+name+'.');};
document.getElementById('v159Undo').onclick=function(){if(!club)return;var d=load(club.clubId);var r=(d.players||[]).pop();save(club.clubId,d);status(r?'Removed '+r.footballName+'.':'Nothing to remove.');};
document.getElementById('v159Export').onclick=function(){if(!club)return;var d=load(club.clubId),rows=d.players||[];if(!valid(rows)){status('Export blocked: complete exactly 16 unique sourced identities with at least 2 GK, 4 DEF, 4 MID and 2 FWD.');return;}var out={schemaVersion:1,season:'2026/27',clubId:club.clubId,snapshot:new Date().toISOString().slice(0,10),sourceSummary:'SWOS Studio local Championship identity evidence draft',players:rows},blob=new Blob([JSON.stringify(out,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=club.clubId+'-identity-evidence.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},500);status('Exported schema-complete identity evidence.');};
document.getElementById('v159Import').onclick=function(){document.getElementById('v159File').click();};document.getElementById('v159File').onchange=async function(e){var f=e.target.files?.[0];if(!f)return;try{var d=JSON.parse(await f.text());var target=pending.find(function(c){return c.clubId===d.clubId;});if(d.schemaVersion!==1||d.season!=='2026/27'||!target||!Array.isArray(d.players)||!valid(d.players))throw new Error('File does not pass the active 16-player identity schema');save(d.clubId,{players:d.players});club=target;sel.value=d.clubId;status('Imported '+target.clubName+' identity evidence.');}catch(err){status('Import rejected: '+(err?.message||err));}finally{e.target.value='';}};
return true;}
async function apply(){try{var r=await fetch(QUEUE_URL,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);q=await r.json();render();}catch(e){}document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v159-championship-identity-layer')||!html.includes('<title>SWOS Studio v1.59.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Championship identity layer missing.`);
console.log(`SWOS Studio ${BUILD} Championship identity expansion live · ${queue.totals.identityReady}/24 ready · next ${queue.next.clubName} · England ${identities.clubCount}/92 identity clubs.`);
