import fs from 'node:fs';
const FILE='dist/index.html',PACKS='football-db/research-packs.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/championship-research-queue.json',INTAKE='football-db/championship-research-intake.json',VALIDATION='football-db/research-expansion-validation.json',IDENTITIES='football-db/identities.json',MANIFEST='football-db/manifest.json',BUILD='v1.92.0';
for(const file of [FILE,PACKS,COVERAGE,QUEUE,INTAKE,VALIDATION,IDENTITIES,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.91.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.91.0 output was not found.`);
const packs=JSON.parse(fs.readFileSync(PACKS,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8')),identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-research.23')throw new Error(`SWOS Studio ${BUILD} build failed: expected research DB .23; found ${manifest.version}.`);
if(!packs.clubs?.['wolverhampton-wanderers']||Object.keys(packs.clubs['wolverhampton-wanderers'].players||{}).length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Wolves research pack missing or incomplete.`);
const identityNames=new Set((identities.clubs?.['wolverhampton-wanderers']||[]).map(p=>p.footballName)),researchNames=new Set(Object.keys(packs.clubs['wolverhampton-wanderers'].players||{}));
if(identityNames.has('Santiago Bueno')||researchNames.has('Santiago Bueno'))throw new Error(`SWOS Studio ${BUILD} build failed: loaned Santiago Bueno survived the Wolves correction.`);
if(!identityNames.has('Toti Gomes')||!researchNames.has('Toti Gomes'))throw new Error(`SWOS Studio ${BUILD} build failed: current Wolves defender Toti Gomes is missing.`);
if(identityNames.size!==16||researchNames.size!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Wolves identity/research sets must both contain exactly 16 players.`);
for(const name of identityNames)if(!researchNames.has(name))throw new Error(`SWOS Studio ${BUILD} build failed: Wolves research pack is missing identity player ${name}.`);
if(packs.packCount!==43||packs.playerCount!==688)throw new Error(`SWOS Studio ${BUILD} build failed: expected 43 research packs / 688 players; found ${packs.packCount} / ${packs.playerCount}.`);
if(pl?.researchReady!==20||champ?.identityReady!==24||champ?.researchReady!==23)throw new Error(`SWOS Studio ${BUILD} build failed: expected PL 20/20 and Championship 23/24 research.`);
if(queue.progress?.researchReadyClubs!==23||queue.totals?.clubs!==1||queue.totals?.stagedPlayers!==16||queue.totals?.requiredEvidenceCells!==48||queue.next?.clubId!=='wrexham')throw new Error(`SWOS Studio ${BUILD} build failed: pending Championship queue should contain Wrexham only.`);
if(intake.progress?.researchReadyClubs!==23||intake.progress?.researchPendingClubs!==1||intake.totals?.clubs!==1||intake.totals?.players!==16||intake.totals?.requiredEvidenceCells!==48)throw new Error(`SWOS Studio ${BUILD} build failed: Championship intake progress is stale.`);
if(validation.status!=='pass'||validation.divisions?.premierLeague?.researchReady!==20||validation.divisions?.championship?.researchReady!==23||validation.totals?.researchClubs!==43||validation.totals?.researchPlayers!==688)throw new Error(`SWOS Studio ${BUILD} build failed: research expansion validation is stale.`);
if(manifest.installation?.teamWriteReady!==false||manifest.installation?.careerWriteReady!==false)throw new Error(`SWOS Studio ${BUILD} build failed: binary write locks changed unexpectedly.`);
html=html.replace('<title>SWOS Studio v1.91.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={champReady:23,totalResearchClubs:43,totalResearchPlayers:688,next:queue.next.clubName},embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v192-wolves-research-layer">
(function(){'use strict';var BUILD='v1.92.0',META=${embedded};
function render(){var anchor=document.getElementById('v191-west-ham-research')||document.getElementById('v190-west-brom-research');if(!anchor)return false;
if(!document.getElementById('v192-wolves-research')){var box=document.createElement('div');box.id='v192-wolves-research';box.className='card stack';box.innerHTML='<strong>✅ Wolverhampton Wanderers research pack promoted</strong><span class="about">The post-window guard removes Santiago Bueno after his Club América loan and replaces him one-for-one with current Wolves centre-back Toti Gomes before publication.</span><span class="about">Championship research coverage: <b>'+META.champReady+' / 24</b>. England now carries <b>'+META.totalResearchClubs+' research-ready clubs / '+META.totalResearchPlayers+' researched players</b>.</span><span class="about">Final evidence target: <b>'+META.next+'</b>. One Championship club remains.</span><span class="feature-status available">23 / 24 CHAMPIONSHIP RESEARCH READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v192-release-card')){var a=document.getElementById('v191-release-card')||document.getElementById('v190-release-card');if(a){var c=document.createElement('div');c.id='v192-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.92.0 — Wolves roster correction + research promotion</strong><span class="about">• Santiago Bueno is removed after his 11 September loan to Club América.</span><span class="about">• Toti Gomes restores the current centre-back slot without changing role balance.</span><span class="about">• Enso González is explicitly mapped as LW/LM rather than generic attack.</span><span class="about">• Championship research reaches 23 / 24.</span><span class="about">• Wrexham is the final Championship evidence target: 16 players / 48 mandatory cells remain.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v192-wolves-research-layer')||!html.includes('<title>SWOS Studio v1.92.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Wolves research layer missing.`);
console.log(`SWOS Studio v1.92.0 Wolves research promotion complete · Championship 23/24 · all research 43 clubs / 688 players · next ${queue.next.clubName} · binary writes locked.`);
