import fs from 'node:fs';
const FILE='dist/index.html',PACKS='football-db/research-packs.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/championship-research-queue.json',INTAKE='football-db/championship-research-intake.json',VALIDATION='football-db/research-expansion-validation.json',IDENTITIES='football-db/identities.json',MANIFEST='football-db/manifest.json',BUILD='v1.91.0';
for(const file of [FILE,PACKS,COVERAGE,QUEUE,INTAKE,VALIDATION,IDENTITIES,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.90.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.90.0 output was not found.`);
const packs=JSON.parse(fs.readFileSync(PACKS,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8')),identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-research.22')throw new Error(`SWOS Studio ${BUILD} build failed: expected research DB .22; found ${manifest.version}.`);
if(!packs.clubs?.['west-ham-united']||Object.keys(packs.clubs['west-ham-united'].players||{}).length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: West Ham research pack missing or incomplete.`);
const identityNames=new Set((identities.clubs?.['west-ham-united']||[]).map(p=>p.footballName)),researchNames=new Set(Object.keys(packs.clubs['west-ham-united'].players||{}));
for(const stale of ['El Hadji Malick Diouf','Jean-Clair Todibo','Aaron Wan-Bissaka','James Ward-Prowse'])if(identityNames.has(stale)||researchNames.has(stale))throw new Error(`SWOS Studio ${BUILD} build failed: stale West Ham player ${stale} survived correction.`);
for(const current of ['Morato','Joel Veltman','Ollie Scarles','Arne Engels'])if(!identityNames.has(current)||!researchNames.has(current))throw new Error(`SWOS Studio ${BUILD} build failed: corrected West Ham player ${current} is missing.`);
if(identityNames.size!==16||researchNames.size!==16)throw new Error(`SWOS Studio ${BUILD} build failed: West Ham identity/research sets must both contain exactly 16 players.`);
for(const name of identityNames)if(!researchNames.has(name))throw new Error(`SWOS Studio ${BUILD} build failed: West Ham research pack is missing identity player ${name}.`);
if(packs.packCount!==42||packs.playerCount!==672)throw new Error(`SWOS Studio ${BUILD} build failed: expected 42 research packs / 672 players; found ${packs.packCount} / ${packs.playerCount}.`);
if(pl?.researchReady!==20||champ?.identityReady!==24||champ?.researchReady!==22)throw new Error(`SWOS Studio ${BUILD} build failed: expected PL 20/20 and Championship 22/24 research.`);
if(queue.progress?.researchReadyClubs!==22||queue.totals?.clubs!==2||queue.totals?.stagedPlayers!==32||queue.totals?.requiredEvidenceCells!==96||queue.next?.clubId!=='wolverhampton-wanderers')throw new Error(`SWOS Studio ${BUILD} build failed: pending Championship queue should be 2 clubs with Wolverhampton Wanderers next.`);
if(intake.progress?.researchReadyClubs!==22||intake.progress?.researchPendingClubs!==2||intake.totals?.clubs!==2||intake.totals?.players!==32||intake.totals?.requiredEvidenceCells!==96)throw new Error(`SWOS Studio ${BUILD} build failed: Championship intake progress is stale.`);
if(validation.status!=='pass'||validation.divisions?.premierLeague?.researchReady!==20||validation.divisions?.championship?.researchReady!==22||validation.totals?.researchClubs!==42||validation.totals?.researchPlayers!==672)throw new Error(`SWOS Studio ${BUILD} build failed: research expansion validation is stale.`);
if(manifest.installation?.teamWriteReady!==false||manifest.installation?.careerWriteReady!==false)throw new Error(`SWOS Studio ${BUILD} build failed: binary write locks changed unexpectedly.`);
html=html.replace('<title>SWOS Studio v1.90.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={champReady:22,totalResearchClubs:42,totalResearchPlayers:672,next:queue.next.clubName},embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v191-west-ham-research-layer">
(function(){'use strict';var BUILD='v1.91.0',META=${embedded};
function render(){var anchor=document.getElementById('v190-west-brom-research')||document.getElementById('v189-watford-research');if(!anchor)return false;
if(!document.getElementById('v191-west-ham-research')){var box=document.createElement('div');box.id='v191-west-ham-research';box.className='card stack';box.innerHTML='<strong>✅ West Ham United research pack promoted</strong><span class="about">Four stale selected identities are removed before publication. Current first-team players Morato, Veltman, Scarles and Engels restore the exact role-balanced 16.</span><span class="about">Championship research coverage: <b>'+META.champReady+' / 24</b>. England now carries <b>'+META.totalResearchClubs+' research-ready clubs / '+META.totalResearchPlayers+' researched players</b>.</span><span class="about">Next evidence target: <b>'+META.next+'</b>. Only two Championship clubs remain.</span><span class="feature-status available">22 / 24 CHAMPIONSHIP RESEARCH READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v191-release-card')){var a=document.getElementById('v190-release-card')||document.getElementById('v189-release-card');if(a){var c=document.createElement('div');c.id='v191-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.91.0 — West Ham current-squad correction + research promotion</strong><span class="about">• Diouf, Todibo, Wan-Bissaka and Ward-Prowse are excluded from the current selected 16.</span><span class="about">• Morato, Joël Veltman, Ollie Scarles and Arne Engels replace them one-for-one by broad role.</span><span class="about">• Maxwel Cornet\'s age is recalculated to 30 on the 27 September snapshot.</span><span class="about">• Championship research reaches 22 / 24; Wolves is next.</span><span class="about">• Just 32 players / 96 mandatory evidence cells remain.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v191-west-ham-research-layer')||!html.includes('<title>SWOS Studio v1.91.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: West Ham research layer missing.`);
console.log(`SWOS Studio v1.91.0 West Ham research promotion complete · Championship 22/24 · all research 42 clubs / 672 players · next ${queue.next.clubName} · binary writes locked.`);
