import fs from 'node:fs';

const FILE='dist/index.html',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/identity-expansion-queue.json',INTAKE='football-db/identity-intake.json',MANIFEST='football-db/manifest.json',VALIDATION='football-db/validation.json';
const BUILD='v1.65.0';
for(const file of [FILE,IDENTITIES,COVERAGE,QUEUE,INTAKE,MANIFEST,VALIDATION])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');if(!html.includes('<title>SWOS Studio v1.64.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.64.0 output was not found.`);
const identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-identity.36')throw new Error(`SWOS Studio ${BUILD} build failed: expected england identity DB .36; found ${manifest.version}.`);
if(!Array.isArray(identities.clubs?.['sheffield-united'])||identities.clubs['sheffield-united'].length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Sheffield United is not a validated 16-player identity pack.`);
if(identities.clubCount!==36||identities.playerCount!==631||identities.divisionCoverage?.championship?.clubs!==16||identities.divisionCoverage?.championship?.players!==256)throw new Error(`SWOS Studio ${BUILD} build failed: expected 36 England identity clubs / 631 players with 16 Championship clubs.`);
if(champ?.identityReady!==16||champ?.researchReady!==0||pl?.identityReady!==20||pl?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: expected Championship 16 identity-ready / 0 research-ready and Premier League 20 / 20.`);
if(coverage.summary?.identityReady!==36||coverage.summary?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: England coverage summary is inconsistent.`);
if(queue.totals?.identityReady!==16||queue.totals?.evidenceRequired!==8||queue.next?.clubId!=='southampton')throw new Error(`SWOS Studio ${BUILD} build failed: Championship queue should advance to Southampton.`);
if(intake.totals?.identityReady!==16||intake.next?.clubId!=='southampton')throw new Error(`SWOS Studio ${BUILD} build failed: final identity intake should show sixteen published clubs and Southampton next.`);
if(validation.status!=='pass'||validation.totals?.identityClubs!==36||validation.totals?.championshipIdentityClubs!==16)throw new Error(`SWOS Studio ${BUILD} build failed: identity expansion validation is stale.`);
html=html.replace('<title>SWOS Studio v1.64.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={englandIdentityClubs:identities.clubCount,englandIdentityPlayers:identities.playerCount,champReady:champ.identityReady,next:queue.next.clubName,plResearch:pl.researchReady,databaseVersion:manifest.version};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v165-sheffield-united-layer">
(function(){
'use strict';var BUILD='v1.65.0',META=${embedded};function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function render(){var panel=document.getElementById('v159-championship-identity');if(panel){var head=panel.querySelector('.v159-head div');if(head)head.innerHTML='<strong>🏆 Championship Identity Expansion — '+META.champReady+' / 24 Complete</strong><p>Sheffield United has cleared the guarded current-squad pipeline. Two thirds of the Championship is now identity-ready with research still held behind the evidence gate.</p>';var stats=panel.querySelector('.v159-stats');if(stats)stats.innerHTML='<div class="v159-stat"><small>England identity</small><b>'+META.englandIdentityClubs+' / 92</b></div><div class="v159-stat"><small>Championship ready</small><b>'+META.champReady+' / 24</b></div><div class="v159-stat"><small>PL research</small><b>'+META.plResearch+' / 20 ✓</b></div><div class="v159-stat"><small>Next club</small><b>'+esc(META.next)+'</b></div>';}
var anchor=document.getElementById('v164-qpr-summary')||document.getElementById('v163-preston-summary')||panel;if(!anchor)return false;if(!document.getElementById('v165-sheffield-united-summary')){var box=document.createElement('div');box.id='v165-sheffield-united-summary';box.className='card stack';box.innerHTML='<strong>Sheffield United identity pack validated</strong><span class="about">A current 2026/27 Sheffield United 16-player identity pack has passed the evidence intake and promotion guard using current squad and official shirt-personalisation cross-checks.</span><span class="about">England now carries '+META.englandIdentityPlayers+' selected identities across '+META.englandIdentityClubs+' clubs. Championship coverage stands at '+META.champReady+' / 24, with '+esc(META.next)+' next.</span><span class="feature-status available">16 / 24 IDENTITY READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v165-release-card')){var a=document.getElementById('v164-release-card')||document.getElementById('v163-release-card');if(a){var c=document.createElement('div');c.id='v165-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.65.0 — Sheffield United identity pack</strong><span class="about">• Sheffield United passes the evidence-gated 16-player current-squad pipeline.</span><span class="about">• Championship identity coverage reaches 16 / 24; England reaches 36 / 92 clubs and 631 selected identities.</span><span class="about">• The new source-evidence preflight validator checks every Championship evidence file before promotion begins.</span><span class="about">• The next identity target is '+esc(META.next)+'.</span><span class="about">• Premier League research remains complete at 20 / 20; Championship research remains intentionally blocked.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');if(!html.includes('swos-v165-sheffield-united-layer')||!html.includes('<title>SWOS Studio v1.65.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Sheffield United layer missing.`);
console.log(`SWOS Studio ${BUILD} Sheffield United identity expansion complete · 16/24 ready · England ${identities.clubCount}/92 identity clubs · next ${queue.next.clubName}.`);
