import fs from 'node:fs';

const FILE='dist/index.html';
const BUILD='v1.42.0';
if(!fs.existsSync(FILE))throw new Error('SWOS Studio v1.42.0 build failed: dist/index.html is missing.');
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.41.0</title>'))throw new Error('SWOS Studio v1.42.0 build failed: expected v1.41.0 output was not found.');
html=html.replace('<title>SWOS Studio v1.41.0</title>','<title>SWOS Studio v1.42.0</title>');
html=html.replaceAll("var BUILD='v1.41.0';","var BUILD='v1.42.0';");

const validateMarker=`  function validateBundle(m,v,i,p){\n    if(!m||!m.version||!m.databaseId)throw new Error('Published database manifest is invalid.');`;
if(!html.includes(validateMarker))throw new Error('SWOS Studio v1.42.0 build failed: v1.41 validation marker was not found.');
const validateReplacement=`  function versionParts(v){return String(v||'0').replace(/^v/i,'').split('.').map(function(x){var n=parseInt(x,10);return Number.isFinite(n)?n:0;});}\n  function versionAtLeast(current,minimum){var a=versionParts(current),b=versionParts(minimum),n=Math.max(a.length,b.length);for(var x=0;x<n;x++){var av=a[x]||0,bv=b[x]||0;if(av>bv)return true;if(av<bv)return false;}return true;}\n  async function rawJson(url){var r=await fetch(url+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(url+' returned HTTP '+r.status);var text=await r.text();try{return{text:text,data:JSON.parse(text)};}catch(e){throw new Error(url+' returned invalid JSON.');}}\n  async function sha256Text(text){if(!window.crypto||!window.crypto.subtle||typeof TextEncoder==='undefined')return null;var bytes=new TextEncoder().encode(text),hash=await window.crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(function(b){return b.toString(16).padStart(2,'0');}).join('');}\n\n  function validateBundle(m,v,i,p){\n    if(!m||!m.version||!m.databaseId)throw new Error('Published database manifest is invalid.');\n    if(m.minimumStudioVersion&&!versionAtLeast(BUILD,m.minimumStudioVersion))throw new Error('Football data '+m.version+' requires SWOS Studio v'+m.minimumStudioVersion+' or newer. Update Studio before installing this database.');`;
html=html.replace(validateMarker,validateReplacement);

const downloadStart=html.indexOf('  async function downloadSnapshot(){');
const downloadEnd=html.indexOf('\n\n  function applySnapshot(s){',downloadStart);
if(downloadStart<0||downloadEnd<0)throw new Error('SWOS Studio v1.42.0 build failed: v1.41 downloadSnapshot block was not found.');
const downloadReplacement=`  async function downloadSnapshot(){\n    var all=await Promise.all([rawJson(MANIFEST),rawJson(VALIDATION),rawJson(IDENTITIES),rawJson(PACKS)]);\n    var m=all[0].data,v=all[1].data,i=all[2].data,p=all[3].data;\n    validateBundle(m,v,i,p);\n    var integrityState='server-validated',expected=v&&v.integrity&&v.integrity.resources||null;\n    if(expected&&String(v.integrity.algorithm||'').toUpperCase()==='SHA-256'){\n      var identityHash=await sha256Text(all[2].text),packHash=await sha256Text(all[3].text);\n      if(identityHash&&packHash){\n        if(identityHash!==expected.verifiedIdentities?.sha256)throw new Error('Identity feed integrity check failed. The download does not match the validated published file.');\n        if(packHash!==expected.researchPacks?.sha256)throw new Error('Research-pack integrity check failed. The download does not match the validated published file.');\n        integrityState='sha256-verified';\n      }\n    }\n    latestManifest=m;\n    return {version:m.version,databaseId:m.databaseId,season:m.season,publishedAt:m.publishedAt,minimumStudioVersion:m.minimumStudioVersion||null,installedAt:new Date().toISOString(),validation:{status:v.status,checks:v.totals&&v.totals.checks||null,integrity:integrityState},identities:i,researchPacks:p,manifest:m};\n  }`;
html=html.slice(0,downloadStart)+downloadReplacement+html.slice(downloadEnd);

const oldSafe=`<div class=\"db-update-safe\"><b>Safe boundary:</b> this only changes Studio\\'s football-data snapshot. It does not alter TEAM.* files and it never injects real-world data into an existing .CAR career.</div>`;
const newSafe=`<div class=\"db-update-safe\"><b>Safe boundary:</b> this only changes Studio\\'s football-data snapshot. It does not alter TEAM.* files and it never injects real-world data into an existing .CAR career.<br><b>Compatibility + integrity:</b> Studio refuses a database that requires a newer app version, and verifies published SHA-256 hashes when Web Crypto is available.</div>`;
if(html.includes(oldSafe))html=html.replace(oldSafe,newSafe);

const css=`\n<style id="swos-v142-integrity-styles">\n  .integrity-strip{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.integrity-pill{border:1px solid rgba(66,209,132,.45);background:rgba(66,209,132,.06);border-radius:999px;padding:5px 8px;font-size:8px;font-weight:900;color:var(--green)}\n</style>`;
html=html.replace('</head>',css+'\n</head>');

const js=String.raw`\n<script id="swos-v142-integrity-layer">\n(function(){\n  'use strict';\n  var BUILD='v1.42.0';\n  function decorate(){\n    var card=document.getElementById('v141-db-update');if(!card)return;\n    var strip=document.getElementById('v142-integrity-strip');if(!strip){strip=document.createElement('div');strip.id='v142-integrity-strip';strip.className='integrity-strip';strip.innerHTML='<span class="integrity-pill">✓ Studio compatibility gate</span><span class="integrity-pill">✓ SHA-256 resource integrity</span><span class="integrity-pill">✓ Existing careers isolated</span>';var safe=card.querySelector('.db-update-safe');if(safe)safe.insertAdjacentElement('beforebegin',strip);else card.appendChild(strip);}\n  }\n  function releaseNotes(){\n    if(document.getElementById('v142-release-card'))return;\n    var anchor=document.getElementById('v141-release-card')||document.getElementById('v140-release-card');if(!anchor)return;\n    var card=document.createElement('div');card.id='v142-release-card';card.className='card stack v133-release-card';\n    card.innerHTML='<strong>New in v1.42.0 — Database compatibility & integrity</strong><span class="about">• The published validation report now carries SHA-256 hashes for identity, research-pack, squad-model and schema resources.</span><span class="about">• Football-data installation verifies the downloaded identity and research files against those hashes on supported browsers.</span><span class="about">• A database can now declare a minimum SWOS Studio version; an incompatible database is refused before it becomes active.</span><span class="about">• The installed snapshot records whether integrity was SHA-256 verified or server-build validated.</span><span class="about">• All existing TEAM.* and .CAR isolation rules remain unchanged.</span>';\n    anchor.insertAdjacentElement('beforebegin',card);\n  }\n  function apply(){document.title='SWOS Studio '+BUILD;var badge=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(badge)badge.textContent=BUILD;releaseNotes();decorate();}\n  var queued=false;function queue(){if(queued)return;queued=true;requestAnimationFrame(function(){try{apply();}finally{queued=false;}});}\n  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',queue,{once:true});else queue();\n  new MutationObserver(function(){if(document.getElementById('v141-db-update')&&!document.getElementById('v142-integrity-strip'))queue();}).observe(document.body,{childList:true,subtree:true});\n})();\n</script>`;
html=html.replace('</body>',js+'\n</body>');

fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('sha256Text')||!html.includes('minimumStudioVersion')||!html.includes('SHA-256 resource integrity'))throw new Error('SWOS Studio v1.42.0 build failed: compatibility/integrity layer was not installed.');
console.log('SWOS Studio '+BUILD+' database compatibility and integrity build complete.');
