import fs from 'node:fs';

const FILE='dist/index.html',QUEUE='football-db/league-two-research-queue.json',INTAKE='football-db/league-two-research-intake.json',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',PACKS='football-db/research-packs.json',VALIDATION='football-db/research-expansion-validation.json',MANIFEST='football-db/manifest.json',BUILD='v1.98.0';
for(const file of [FILE,QUEUE,INTAKE,IDENTITIES,COVERAGE,PACKS,VALIDATION,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.97.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.97.0 output.`);
const queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),packs=JSON.parse(fs.readFileSync(PACKS,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));
const pl=coverage.divisions?.find(d=>d.code===0),champ=coverage.divisions?.find(d=>d.code===1),l1=coverage.divisions?.find(d=>d.code===2),l2=coverage.divisions?.find(d=>d.code===3);
if(manifest.version!=='2026.27-england-identity.92'||identities.clubCount!==92||identities.playerCount!==1527)throw new Error(`SWOS Studio ${BUILD} build failed: completed England identity foundation regressed.`);
if(pl?.researchReady!==20||champ?.researchReady!==24||l1?.researchReady!==24||l2?.identityReady!==24||l2?.researchReady!==0)throw new Error(`SWOS Studio ${BUILD} build failed: division coverage totals are inconsistent.`);
if(packs.packCount!==68||packs.playerCount!==1088)throw new Error(`SWOS Studio ${BUILD} build failed: research must remain at 68 clubs / 1,088 players before the first League Two promotion.`);
if(queue.status!=='active'||queue.progress?.researchReadyClubs!==0||queue.progress?.researchPendingClubs!==24||queue.totals?.clubs!==24||queue.totals?.stagedPlayers!==384||queue.totals?.requiredEvidenceCells!==1152||queue.next?.clubId!=='accrington-stanley')throw new Error(`SWOS Studio ${BUILD} build failed: League Two queue must contain 24 clubs / 384 players / 1,152 cells starting at Accrington Stanley.`);
if(intake.progress?.researchReadyClubs!==0||intake.progress?.researchPendingClubs!==24||intake.totals?.clubs!==24||intake.totals?.players!==384||intake.totals?.requiredEvidenceCells!==1152||intake.totals?.requiredEvidenceCellsComplete!==0||intake.totals?.promotionReadyClubs!==0||intake.nextEvidenceRequired?.clubId!=='accrington-stanley')throw new Error(`SWOS Studio ${BUILD} build failed: League Two intake foundation is stale.`);
if(validation.status!=='pass'||validation.divisions?.premierLeague?.researchReady!==20||validation.divisions?.championship?.researchReady!==24||validation.divisions?.leagueOne?.researchReady!==24||validation.divisions?.leagueTwo?.researchReady!==0||validation.totals?.researchClubs!==68||validation.totals?.researchPlayers!==1088)throw new Error(`SWOS Studio ${BUILD} build failed: England research validation did not pass the League Two foundation.`);
if(manifest.resources?.leagueTwoResearchQueue!==QUEUE||manifest.resources?.leagueTwoResearchIntake!==INTAKE||manifest.resources?.leagueTwoResearchEvidenceSchema!=='football-db/league-two-research-evidence/schema-v1.json')throw new Error(`SWOS Studio ${BUILD} build failed: League Two manifest resources were not published under division-correct keys.`);
if(manifest.resources?.leagueOneResearchQueue!=='football-db/league-one-research-queue.json'||manifest.resources?.leagueOneResearchIntake!=='football-db/league-one-research-intake.json')throw new Error(`SWOS Studio ${BUILD} build failed: League One manifest resources were overwritten.`);
if(manifest.installation?.teamWriteReady!==false||manifest.installation?.careerWriteReady!==false)throw new Error(`SWOS Studio ${BUILD} build failed: binary write locks changed.`);

html=html.replace('<title>SWOS Studio v1.97.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={clubs:queue.totals.clubs,players:queue.totals.stagedPlayers,cells:queue.totals.requiredEvidenceCells,next:queue.next.clubName,researchClubs:packs.packCount,researchPlayers:packs.playerCount};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v198-league-two-research-foundation-layer">
(function(){
'use strict';var BUILD='v1.98.0',META=${embedded};
function render(){var anchor=document.getElementById('v197-league-two-identity-complete')||document.getElementById('v196-league-one-research-complete');if(!anchor)return false;
if(!document.getElementById('v198-league-two-research-foundation')){var box=document.createElement('div');box.id='v198-league-two-research-foundation';box.className='card stack';box.innerHTML='<strong>🔬 League Two research pipeline — staged</strong><span class="about">All <b>'+META.clubs+' League Two clubs / '+META.players+' selected players</b> are now staged behind the exact evidence gate. Every player needs a sourced age, published market value and exact SWOS position before a club can promote.</span><span class="about">The queue contains <b>'+META.cells+' mandatory evidence cells</b>. First target: <b>'+META.next+'</b>. League Two remains 0 / 24 research-ready until a complete 16-player pack passes validation.</span><span class="about">England remains at <b>'+META.researchClubs+' research-ready clubs / '+META.researchPlayers+' researched players</b>. No values are guessed and no TEAM.* or established .CAR bytes are touched.</span><span class="feature-status beta">LEAGUE TWO RESEARCH FOUNDATION READY</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v198-release-card')){var a=document.getElementById('v197-release-card')||document.getElementById('v196-release-card');if(a){var c=document.createElement('div');c.id='v198-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.98.0 — League Two research foundation</strong><span class="about">• 24 identity-ready clubs are staged into a deterministic research queue.</span><span class="about">• 384 selected players create 1,152 required age, market-value and exact-position evidence cells.</span><span class="about">• Queue, intake, schema, promoter and bounded completion guards are division-aware.</span><span class="about">• Publication and England-wide validation now support incremental League Two packs without overwriting League One resources.</span><span class="about">• Accrington Stanley is the first evidence target.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');
fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v198-league-two-research-foundation-layer')||!html.includes('<title>SWOS Studio v1.98.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: League Two research foundation layer missing.`);
console.log(`SWOS Studio v1.98.0 League Two research foundation staged · 24 clubs / 384 players / 1,152 cells · next ${queue.next.clubName} · binary writes locked.`);
