import fs from 'node:fs';

const FILE='dist/index.html',QUEUE='football-db/league-one-identity-expansion-queue.json',INTAKE='football-db/league-one-identity-intake.json',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',PACKS='football-db/research-packs.json',VALIDATION='football-db/validation.json',RESEARCH_VALIDATION='football-db/research-expansion-validation.json',MANIFEST='football-db/manifest.json',BUILD='v1.95.0';
for(const file of [FILE,QUEUE,INTAKE,IDENTITIES,COVERAGE,PACKS,VALIDATION,RESEARCH_VALIDATION,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');if(!html.includes('<title>SWOS Studio v1.94.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.94.0 output.`);
const queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),packs=JSON.parse(fs.readFileSync(PACKS,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8')),researchValidation=JSON.parse(fs.readFileSync(RESEARCH_VALIDATION,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),pl=coverage.divisions?.find(d=>d.code===0),champ=coverage.divisions?.find(d=>d.code===1),l1=coverage.divisions?.find(d=>d.code===2),l2=coverage.divisions?.find(d=>d.code===3);
if(manifest.version!=='2026.27-england-identity.68'||identities.clubCount!==68||identities.playerCount!==1143)throw new Error(`SWOS Studio ${BUILD} build failed: expected England identity coverage 68 clubs / 1,143 players.`);
if(identities.divisionCoverage?.leagueOne?.clubs!==24||identities.divisionCoverage?.leagueOne?.players!==384||l1?.identityReady!==24||l1?.researchReady!==0||l2?.identityReady!==0)throw new Error(`SWOS Studio ${BUILD} build failed: League One identity completion totals are stale.`);
if(pl?.researchReady!==20||champ?.identityReady!==24||champ?.researchReady!==24||packs.packCount!==44||packs.playerCount!==704)throw new Error(`SWOS Studio ${BUILD} build failed: completed upper-division research was not preserved.`);
if(queue.status!=='complete'||queue.totals?.identityReady!==24||queue.totals?.evidenceRequired!==0||queue.next!==null)throw new Error(`SWOS Studio ${BUILD} build failed: League One identity queue is not closed.`);
if(intake.status!=='complete'||intake.totals?.identityReady!==24||intake.totals?.promotionReadyClubs!==0||intake.next!==null)throw new Error(`SWOS Studio ${BUILD} build failed: League One identity intake is not closed.`);
if(validation.status!=='pass'||validation.totals?.leagueOneIdentityClubs!==24||validation.totals?.leagueOneIdentityPlayers!==384||researchValidation.status!=='pass'||researchValidation.databaseVersion!==manifest.version||researchValidation.totals?.researchClubs!==44||researchValidation.totals?.researchPlayers!==704)throw new Error(`SWOS Studio ${BUILD} build failed: division-aware validations are stale.`);
if(manifest.installation?.teamWriteReady!==false||manifest.installation?.careerWriteReady!==false)throw new Error(`SWOS Studio ${BUILD} build failed: binary write locks changed.`);
html=html.replace('<title>SWOS Studio v1.94.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={identityClubs:identities.clubCount,identityPlayers:identities.playerCount,researchClubs:packs.packCount,researchPlayers:packs.playerCount};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v195-league-one-identity-complete-layer">
(function(){
'use strict';var BUILD='v1.95.0',META=${embedded};
function render(){var anchor=document.getElementById('v194-league-one-foundation')||document.getElementById('v193-research');if(!anchor)return false;
if(!document.getElementById('v195-league-one-complete')){var box=document.createElement('div');box.id='v195-league-one-complete';box.className='card stack';box.innerHTML='<strong>🏆 League One identity expansion — complete</strong><span class="about">All <b>24 / 24 League One clubs</b> now expose evidence-gated 16-player 2026/27 identity packs. The League One identity queue and intake have closed cleanly.</span><span class="about">England identity coverage is now <b>'+META.identityClubs+' / 92 clubs</b> with <b>'+META.identityPlayers+' selected identities</b>.</span><span class="about">Premier League and Championship research remain unchanged at <b>'+META.researchClubs+' clubs / '+META.researchPlayers+' players</b>. The next safe phase is League One age, market-value and exact-position research.</span><span class="feature-status available">24 / 24 LEAGUE ONE IDENTITIES READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v195-release-card')){var a=document.getElementById('v194-release-card')||document.getElementById('v193-release-card');if(a){var c=document.createElement('div');c.id='v195-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.95.0 — League One identity stage complete</strong><span class="about">• All 24 clubs promoted through the separate League One evidence guard.</span><span class="about">• 384 selected players passed exact-16, unique-name, nationality, source and role-balance validation.</span><span class="about">• England identity coverage reaches 68 / 92 clubs and 1,143 selected players.</span><span class="about">• League One research remains 0 / 24 until its separate evidence pipeline is built.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v195-league-one-identity-complete-layer')||!html.includes('<title>SWOS Studio v1.95.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: completion UI layer missing.`);
console.log('SWOS Studio v1.95.0 League One identity completion · 24/24 · England 68/92 / 1,143 identities · research remains 44 clubs / 704 players · binary writes locked.');
