import fs from 'node:fs';
const FILE='dist/index.html',PACKS='football-db/research-packs.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/championship-research-queue.json',INTAKE='football-db/championship-research-intake.json',VALIDATION='football-db/research-expansion-validation.json',IDENTITIES='football-db/identities.json',MANIFEST='football-db/manifest.json',BUILD='v1.89.0';
for(const file of [FILE,PACKS,COVERAGE,QUEUE,INTAKE,VALIDATION,IDENTITIES,MANIFEST])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');
if(!html.includes('<title>SWOS Studio v1.88.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.88.0 output was not found.`);
const packs=JSON.parse(fs.readFileSync(PACKS,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8')),identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-research.20')throw new Error(`SWOS Studio ${BUILD} build failed: expected research DB .20; found ${manifest.version}.`);
if(!packs.clubs?.watford||Object.keys(packs.clubs.watford.players||{}).length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Watford research pack missing or incomplete.`);
const identityNames=new Set((identities.clubs?.watford||[]).map(p=>p.footballName)),researchNames=new Set(Object.keys(packs.clubs.watford.players||{}));
if(identityNames.size!==16||researchNames.size!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Watford identity/research sets must both contain exactly 16 players.`);
for(const name of identityNames)if(!researchNames.has(name))throw new Error(`SWOS Studio ${BUILD} build failed: Watford research pack is missing identity player ${name}.`);
if(packs.clubs.watford.players?.['Jack Grieves']?.position!==7)throw new Error(`SWOS Studio ${BUILD} build failed: Jack Grieves exact research position should be SWOS attack code 7.`);
if(packs.packCount!==40||packs.playerCount!==640)throw new Error(`SWOS Studio ${BUILD} build failed: expected 40 research packs / 640 players; found ${packs.packCount} / ${packs.playerCount}.`);
if(pl?.researchReady!==20||champ?.identityReady!==24||champ?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: expected PL 20/20 and Championship 20/24 research.`);
if(queue.progress?.researchReadyClubs!==20||queue.totals?.clubs!==4||queue.totals?.stagedPlayers!==64||queue.totals?.requiredEvidenceCells!==192||queue.next?.clubId!=='west-bromwich-albion')throw new Error(`SWOS Studio ${BUILD} build failed: pending Championship queue should be 4 clubs with West Bromwich Albion next.`);
if(intake.progress?.researchReadyClubs!==20||intake.progress?.researchPendingClubs!==4||intake.totals?.clubs!==4||intake.totals?.players!==64||intake.totals?.requiredEvidenceCells!==192)throw new Error(`SWOS Studio ${BUILD} build failed: Championship intake progress is stale.`);
if(validation.status!=='pass'||validation.divisions?.premierLeague?.researchReady!==20||validation.divisions?.championship?.researchReady!==20||validation.totals?.researchClubs!==40||validation.totals?.researchPlayers!==640)throw new Error(`SWOS Studio ${BUILD} build failed: research expansion validation is stale.`);
if(manifest.installation?.teamWriteReady!==false||manifest.installation?.careerWriteReady!==false)throw new Error(`SWOS Studio ${BUILD} build failed: binary write locks changed unexpectedly.`);
html=html.replace('<title>SWOS Studio v1.88.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={champReady:20,totalResearchClubs:40,totalResearchPlayers:640,next:queue.next.clubName},embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v189-watford-research-layer">
(function(){'use strict';var BUILD='v1.89.0',META=${embedded};
function render(){var anchor=document.getElementById('v188-swansea-research')||document.getElementById('v187-stoke-research');if(!anchor)return false;
if(!document.getElementById('v189-watford-research')){var box=document.createElement('div');box.id='v189-watford-research';box.className='card stack';box.innerHTML='<strong>✅ Watford research pack promoted</strong><span class="about">Watford has passed the exact-16 evidence gate with current squad verification, sourced values and precise SWOS roles. Jack Grieves is corrected at research level from a broad midfield staging label to his current centre-forward role.</span><span class="about">Championship research coverage: <b>'+META.champReady+' / 24</b>. England now carries <b>'+META.totalResearchClubs+' research-ready clubs / '+META.totalResearchPlayers+' researched players</b>.</span><span class="about">Next evidence target: <b>'+META.next+'</b>. Four Championship clubs remain.</span><span class="feature-status available">20 / 24 CHAMPIONSHIP RESEARCH READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v189-release-card')){var a=document.getElementById('v188-release-card')||document.getElementById('v187-release-card');if(a){var c=document.createElement('div');c.id='v189-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.89.0 — Watford research promotion</strong><span class="about">• Watford becomes the twentieth Championship research-ready club.</span><span class="about">• All 16 current identities carry sourced age, value and exact-position evidence.</span><span class="about">• Jack Grieves is mapped by current playing role to SWOS attack code 7 rather than preserving a stale broad-group label.</span><span class="about">• Current-club truth remains separate from older valuation pages for summer arrivals such as Omar Traoré.</span><span class="about">• Championship research reaches 20 / 24; West Bromwich Albion is next.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');
if(!html.includes('swos-v189-watford-research-layer')||!html.includes('<title>SWOS Studio v1.89.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Watford research layer missing.`);
console.log(`SWOS Studio v1.89.0 Watford research promotion complete · Championship 20/24 · all research 40 clubs / 640 players · next ${queue.next.clubName} · binary writes locked.`);
