import fs from 'node:fs';

const FILE='dist/index.html',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/identity-expansion-queue.json',INTAKE='football-db/identity-intake.json',MANIFEST='football-db/manifest.json',VALIDATION='football-db/validation.json';
const BUILD='v1.62.0';
for(const file of [FILE,IDENTITIES,COVERAGE,QUEUE,INTAKE,MANIFEST,VALIDATION])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');if(!html.includes('<title>SWOS Studio v1.61.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.61.0 output was not found.`);
const identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-identity.33')throw new Error(`SWOS Studio ${BUILD} build failed: expected england identity DB .33; found ${manifest.version}.`);
if(!Array.isArray(identities.clubs?.portsmouth)||identities.clubs.portsmouth.length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Portsmouth is not a validated 16-player identity pack.`);
if(identities.clubCount!==33||identities.playerCount!==583||identities.divisionCoverage?.championship?.clubs!==13||identities.divisionCoverage?.championship?.players!==208)throw new Error(`SWOS Studio ${BUILD} build failed: expected 33 England identity clubs / 583 players with 13 Championship clubs.`);
if(champ?.identityReady!==13||champ?.researchReady!==0||pl?.identityReady!==20||pl?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: expected Championship 13 identity-ready / 0 research-ready and Premier League 20 / 20.`);
if(coverage.summary?.identityReady!==33||coverage.summary?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: England coverage summary is inconsistent.`);
if(queue.totals?.identityReady!==13||queue.totals?.evidenceRequired!==11||queue.next?.clubId!=='preston-north-end')throw new Error(`SWOS Studio ${BUILD} build failed: Championship queue should advance to Preston North End.`);
if(intake.totals?.identityReady!==13||intake.next?.clubId!=='preston-north-end')throw new Error(`SWOS Studio ${BUILD} build failed: final identity intake should show thirteen published clubs and Preston North End next.`);
if(validation.status!=='pass'||validation.totals?.identityClubs!==33||validation.totals?.championshipIdentityClubs!==13)throw new Error(`SWOS Studio ${BUILD} build failed: identity expansion validation is stale.`);
html=html.replace('<title>SWOS Studio v1.61.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={englandIdentityClubs:identities.clubCount,englandIdentityPlayers:identities.playerCount,champReady:champ.identityReady,champPending:24-champ.identityReady,next:queue.next.clubName,plResearch:pl.researchReady,databaseVersion:manifest.version};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v162-portsmouth-layer">
(function(){
'use strict';var BUILD='v1.62.0',META=${embedded};function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function render(){var panel=document.getElementById('v159-championship-identity');if(panel){var head=panel.querySelector('.v159-head div');if(head)head.innerHTML='<strong>🏆 Championship Identity Expansion — '+META.champReady+' / 24 Complete</strong><p>Portsmouth has now passed the same guarded 16-player evidence pipeline, taking Championship identity coverage beyond halfway without relaxing source, uniqueness or role-balance checks.</p>';var stats=panel.querySelector('.v159-stats');if(stats)stats.innerHTML='<div class="v159-stat"><small>England identity</small><b>'+META.englandIdentityClubs+' / 92</b></div><div class="v159-stat"><small>Championship ready</small><b>'+META.champReady+' / 24</b></div><div class="v159-stat"><small>PL research</small><b>'+META.plResearch+' / 20 ✓</b></div><div class="v159-stat"><small>Next club</small><b>'+esc(META.next)+'</b></div>';}
var anchor=document.getElementById('v161-wave-summary')||panel||document.getElementById('v160-wave-summary');if(!anchor)return false;if(!document.getElementById('v162-portsmouth-summary')){var box=document.createElement('div');box.id='v162-portsmouth-summary';box.className='card stack';box.innerHTML='<strong>Portsmouth identity pack validated</strong><span class="about">A current 2026/27 Portsmouth 16-player identity pack has passed the evidence intake and promotion guard.</span><span class="about">England now carries '+META.englandIdentityPlayers+' selected identities across '+META.englandIdentityClubs+' clubs. Championship coverage stands at '+META.champReady+' / 24, with '+META.next+' next.</span><span class="feature-status available">13 / 24 IDENTITY READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v162-release-card')){var a=document.getElementById('v161-release-card')||document.getElementById('v160-release-card');if(a){var c=document.createElement('div');c.id='v162-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.62.0 — Portsmouth joins the guarded Championship database</strong><span class="about">• Portsmouth passes the evidence-gated 16-player identity pipeline using a current 2026/27 squad snapshot.</span><span class="about">• Championship identity coverage moves to 13 / 24; England reaches 33 / 92 clubs and 583 selected identities.</span><span class="about">• The same source, exact-16, uniqueness, shirt and role-balance validation remains in force.</span><span class="about">• The next identity target is '+esc(META.next)+'.</span><span class="about">• Premier League research remains complete at 20 / 20 clubs; Championship research still waits behind identity completion rather than inventing data.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');if(!html.includes('swos-v162-portsmouth-layer')||!html.includes('<title>SWOS Studio v1.62.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Portsmouth layer missing.`);
console.log(`SWOS Studio ${BUILD} Portsmouth identity expansion complete · 13/24 ready · England ${identities.clubCount}/92 identity clubs · next ${queue.next.clubName}.`);
