import fs from 'node:fs';

const FILE='dist/index.html',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/identity-expansion-queue.json',INTAKE='football-db/identity-intake.json',MANIFEST='football-db/manifest.json',VALIDATION='football-db/validation.json';
const BUILD='v1.63.0';
for(const file of [FILE,IDENTITIES,COVERAGE,QUEUE,INTAKE,MANIFEST,VALIDATION])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');if(!html.includes('<title>SWOS Studio v1.62.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.62.0 output was not found.`);
const identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
if(manifest.version!=='2026.27-england-identity.34')throw new Error(`SWOS Studio ${BUILD} build failed: expected england identity DB .34; found ${manifest.version}.`);
if(!Array.isArray(identities.clubs?.['preston-north-end'])||identities.clubs['preston-north-end'].length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: Preston North End is not a validated 16-player identity pack.`);
if(identities.clubCount!==34||identities.playerCount!==599||identities.divisionCoverage?.championship?.clubs!==14||identities.divisionCoverage?.championship?.players!==224)throw new Error(`SWOS Studio ${BUILD} build failed: expected 34 England identity clubs / 599 players with 14 Championship clubs.`);
if(champ?.identityReady!==14||champ?.researchReady!==0||pl?.identityReady!==20||pl?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: expected Championship 14 identity-ready / 0 research-ready and Premier League 20 / 20.`);
if(coverage.summary?.identityReady!==34||coverage.summary?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: England coverage summary is inconsistent.`);
if(queue.totals?.identityReady!==14||queue.totals?.evidenceRequired!==10||queue.next?.clubId!=='queens-park-rangers')throw new Error(`SWOS Studio ${BUILD} build failed: Championship queue should advance to Queens Park Rangers.`);
if(intake.totals?.identityReady!==14||intake.next?.clubId!=='queens-park-rangers')throw new Error(`SWOS Studio ${BUILD} build failed: final identity intake should show fourteen published clubs and Queens Park Rangers next.`);
if(validation.status!=='pass'||validation.totals?.identityClubs!==34||validation.totals?.championshipIdentityClubs!==14)throw new Error(`SWOS Studio ${BUILD} build failed: identity expansion validation is stale.`);
html=html.replace('<title>SWOS Studio v1.62.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={englandIdentityClubs:identities.clubCount,englandIdentityPlayers:identities.playerCount,champReady:champ.identityReady,next:queue.next.clubName,plResearch:pl.researchReady,databaseVersion:manifest.version};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v163-preston-layer">
(function(){
'use strict';var BUILD='v1.63.0',META=${embedded};function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function render(){var panel=document.getElementById('v159-championship-identity');if(panel){var head=panel.querySelector('.v159-head div');if(head)head.innerHTML='<strong>🏆 Championship Identity Expansion — '+META.champReady+' / 24 Complete</strong><p>Preston North End has passed the guarded current-squad identity pipeline. Fourteen Championship clubs are now identity-ready, with research still deliberately held behind this evidence gate.</p>';var stats=panel.querySelector('.v159-stats');if(stats)stats.innerHTML='<div class="v159-stat"><small>England identity</small><b>'+META.englandIdentityClubs+' / 92</b></div><div class="v159-stat"><small>Championship ready</small><b>'+META.champReady+' / 24</b></div><div class="v159-stat"><small>PL research</small><b>'+META.plResearch+' / 20 ✓</b></div><div class="v159-stat"><small>Next club</small><b>'+esc(META.next)+'</b></div>';}
var anchor=document.getElementById('v162-portsmouth-summary')||document.getElementById('v161-wave-summary')||panel;if(!anchor)return false;if(!document.getElementById('v163-preston-summary')){var box=document.createElement('div');box.id='v163-preston-summary';box.className='card stack';box.innerHTML='<strong>Preston North End identity pack validated</strong><span class="about">A current 2026/27 Preston North End 16-player identity pack has cleared the same evidence intake and promotion guard.</span><span class="about">England now carries '+META.englandIdentityPlayers+' selected identities across '+META.englandIdentityClubs+' clubs. Championship coverage stands at '+META.champReady+' / 24, with '+esc(META.next)+' next.</span><span class="feature-status available">14 / 24 IDENTITY READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v163-release-card')){var a=document.getElementById('v162-release-card')||document.getElementById('v161-release-card');if(a){var c=document.createElement('div');c.id='v163-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.63.0 — Preston North End identity pack</strong><span class="about">• Preston North End passes the evidence-gated 16-player current-squad pipeline.</span><span class="about">• Championship identity coverage moves to 14 / 24; England reaches 34 / 92 clubs and 599 selected identities.</span><span class="about">• Exact-16, source, uniqueness, shirt and role-balance checks remain mandatory.</span><span class="about">• The next identity target is '+esc(META.next)+'.</span><span class="about">• Premier League research remains complete at 20 / 20; Championship research stays blocked until identity coverage is ready.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');if(!html.includes('swos-v163-preston-layer')||!html.includes('<title>SWOS Studio v1.63.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Preston layer missing.`);
console.log(`SWOS Studio ${BUILD} Preston North End identity expansion complete · 14/24 ready · England ${identities.clubCount}/92 identity clubs · next ${queue.next.clubName}.`);
