import fs from 'node:fs';

const FILE='dist/index.html',IDENTITIES='football-db/identities.json',COVERAGE='football-db/coverage.json',QUEUE='football-db/identity-expansion-queue.json',INTAKE='football-db/identity-intake.json',MANIFEST='football-db/manifest.json',VALIDATION='football-db/validation.json';
const BUILD='v1.61.0';
for(const file of [FILE,IDENTITIES,COVERAGE,QUEUE,INTAKE,MANIFEST,VALIDATION])if(!fs.existsSync(file))throw new Error(`SWOS Studio ${BUILD} build failed: missing ${file}.`);
let html=fs.readFileSync(FILE,'utf8');if(!html.includes('<title>SWOS Studio v1.60.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: expected v1.60.0 output was not found.`);
const identities=JSON.parse(fs.readFileSync(IDENTITIES,'utf8')),coverage=JSON.parse(fs.readFileSync(COVERAGE,'utf8')),queue=JSON.parse(fs.readFileSync(QUEUE,'utf8')),intake=JSON.parse(fs.readFileSync(INTAKE,'utf8')),manifest=JSON.parse(fs.readFileSync(MANIFEST,'utf8')),validation=JSON.parse(fs.readFileSync(VALIDATION,'utf8'));
const champ=coverage.divisions?.find(d=>d.code===1),pl=coverage.divisions?.find(d=>d.code===0);
const expectedIds=['birmingham-city','blackburn-rovers','bolton-wanderers','bristol-city','burnley','cardiff-city','charlton-athletic','derby-county','lincoln-city','middlesbrough','millwall','norwich-city'];
if(manifest.version!=='2026.27-england-identity.32')throw new Error(`SWOS Studio ${BUILD} build failed: expected england identity DB .32; found ${manifest.version}.`);
if(identities.clubCount!==32||identities.playerCount!==567||identities.divisionCoverage?.championship?.clubs!==12||identities.divisionCoverage?.championship?.players!==192)throw new Error(`SWOS Studio ${BUILD} build failed: expected 32 England identity clubs / 567 players with 12 Championship clubs.`);
for(const id of expectedIds)if(!Array.isArray(identities.clubs?.[id])||identities.clubs[id].length!==16)throw new Error(`SWOS Studio ${BUILD} build failed: ${id} is not a validated 16-player identity pack.`);
if(champ?.identityReady!==12||champ?.researchReady!==0||pl?.identityReady!==20||pl?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: expected Championship 12 identity-ready / 0 research-ready and Premier League 20 / 20.`);
if(coverage.summary?.identityReady!==32||coverage.summary?.researchReady!==20)throw new Error(`SWOS Studio ${BUILD} build failed: England coverage summary is inconsistent.`);
if(queue.totals?.identityReady!==12||queue.totals?.evidenceRequired!==12||queue.next?.clubId!=='portsmouth')throw new Error(`SWOS Studio ${BUILD} build failed: Championship queue should advance to Portsmouth.`);
if(intake.totals?.identityReady!==12||intake.next?.clubId!=='portsmouth')throw new Error(`SWOS Studio ${BUILD} build failed: final identity intake should show twelve published clubs and Portsmouth next.`);
if(validation.status!=='pass'||validation.totals?.identityClubs!==32||validation.totals?.championshipIdentityClubs!==12)throw new Error(`SWOS Studio ${BUILD} build failed: identity expansion validation is stale.`);
html=html.replace('<title>SWOS Studio v1.60.0</title>',`<title>SWOS Studio ${BUILD}</title>`);
const meta={englandIdentityClubs:identities.clubCount,englandIdentityPlayers:identities.playerCount,champReady:champ.identityReady,champPending:24-champ.identityReady,next:queue.next.clubName,plResearch:pl.researchReady,databaseVersion:manifest.version,wave:['Charlton Athletic','Derby County','Lincoln City','Middlesbrough','Millwall','Norwich City']};
const embedded=JSON.stringify(meta).replace(/</g,'\\u003c');
const js=String.raw`
<script id="swos-v161-championship-wave-layer">
(function(){
'use strict';var BUILD='v1.61.0',META=${embedded};function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function render(){var panel=document.getElementById('v159-championship-identity');if(panel){var head=panel.querySelector('.v159-head div');if(head)head.innerHTML='<strong>🏆 Championship Identity Expansion — 50% Complete</strong><p>Twelve of 24 Championship clubs now have evidence-gated 16-player identity packs. The first half of the division is published without relaxing the source, uniqueness or role-balance gates.</p>';var stats=panel.querySelector('.v159-stats');if(stats)stats.innerHTML='<div class="v159-stat"><small>England identity</small><b>'+META.englandIdentityClubs+' / 92</b></div><div class="v159-stat"><small>Championship ready</small><b>'+META.champReady+' / 24</b></div><div class="v159-stat"><small>PL research</small><b>'+META.plResearch+' / 20 ✓</b></div><div class="v159-stat"><small>Next club</small><b>'+esc(META.next)+'</b></div>';}
var anchor=panel||document.getElementById('v160-wave-summary')||document.getElementById('v1581-static-db-note');if(!anchor)return false;if(!document.getElementById('v161-wave-summary')){var box=document.createElement('div');box.id='v161-wave-summary';box.className='card stack';box.innerHTML='<strong>Championship Wave 2 validated</strong><span class="about">'+META.wave.map(esc).join(' · ')+'</span><span class="about">Championship identity coverage has reached exactly half of the division: '+META.champReady+' / 24 clubs, with '+META.englandIdentityPlayers+' selected identities now available across England. Portsmouth is next.</span><span class="feature-status available">12 / 24 IDENTITY READY ✓</span>';anchor.insertAdjacentElement('afterend',box);}
if(!document.getElementById('v161-release-card')){var a=document.getElementById('v160-release-card')||document.getElementById('v159-release-card');if(a){var c=document.createElement('div');c.id='v161-release-card';c.className='card stack v133-release-card';c.innerHTML='<strong>New in v1.61.0 — Championship identity wave 2</strong><span class="about">• Charlton Athletic, Derby County, Lincoln City, Middlesbrough, Millwall and Norwich City pass the guarded identity pipeline.</span><span class="about">• Championship identity coverage reaches 12 / 24; England reaches 32 / 92 clubs and 567 selected current identities.</span><span class="about">• Source, exact-16, uniqueness, shirt and role-balance validation runs after every individual promotion.</span><span class="about">• The next identity target is '+esc(META.next)+'.</span><span class="about">• Premier League research remains locked complete at 20 / 20 clubs; Championship research has not been fabricated ahead of identity work.</span><span class="about">• TEAM.* and established .CAR binary writes remain locked.</span>';a.insertAdjacentElement('beforebegin',c);}}
document.title='SWOS Studio '+BUILD;var b=document.querySelector('#v133-build-status-panel .build-status-head>.feature-status.beta');if(b)b.textContent=BUILD;return true;}
var tries=0;function apply(){tries++;if(!render()&&tries<20)setTimeout(apply,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
</script>`;
html=html.replace('</body>',js+'\n</body>');fs.writeFileSync(FILE,html,'utf8');if(!html.includes('swos-v161-championship-wave-layer')||!html.includes('<title>SWOS Studio v1.61.0</title>'))throw new Error(`SWOS Studio ${BUILD} build failed: Championship wave 2 layer missing.`);
console.log(`SWOS Studio ${BUILD} Championship identity wave 2 complete · 12/24 ready · England ${identities.clubCount}/92 identity clubs · next ${queue.next.clubName} · ${intake.totals?.promotionReadyClubs||0} further evidence-ready.`);
